'use strict';
const VERSION='4.0.1';
const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat('ru-RU');
const state={manifest:null,map:null,layers:[],filtered:[],currentId:null,currentMeta:null,currentJson:null,currentLayer:null,previousLayer:null,hatchLayer:null,waterLayer:null,riverLayer:null,cache:new Map(),colors:new Map(),selectedLayer:null,selectedFeature:null};
const dom={status:$('status'),category:$('categorySelect'),layerSelect:$('layerSelect'),mode:$('modeSelect'),showWater:$('showWater'),showRivers:$('showRivers'),showPrevious:$('showPrevious'),showHatch:$('showHatch'),showLabels:$('showLabels'),slider:$('timeSlider'),radios:$('radioList'),prev:$('prevBtn'),next:$('nextBtn'),fitLayer:$('fitLayerBtn'),fitProject:$('fitProjectBtn'),download:$('downloadBtn'),layerInfo:$('layerInfo'),featureInfo:$('featureInfo'),schema:$('schemaInfo'),table:$('tableBox'),search:$('tableSearch')};
const palette=['#8dd3c7','#ffffb3','#bebada','#fb8072','#80b1d3','#fdb462','#b3de69','#fccde5','#bc80bd','#ccebc5','#ffed6f','#d9d9d9','#a6cee3','#b2df8a','#fdbf6f','#cab2d6'];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function compact(v,n=160){if(v===null||v===undefined||v==='')return '—';const s=String(v);return s.length>n?s.slice(0,n)+'…':s}
function num(v){const n=Number(v);return Number.isFinite(n)?fmt.format(Math.round(n)):'—'}
function setStatus(txt){dom.status.innerHTML=txt}
function colorFor(v){const k=String(v||'—');if(!state.colors.has(k))state.colors.set(k,palette[state.colors.size%palette.length]);return state.colors.get(k)}
function boundsFromBbox(b){return L.latLngBounds([b[1],b[0]],[b[3],b[2]])}
async function loadJson(path){if(state.cache.has(path))return state.cache.get(path);const r=await fetch(`${path}?v=${VERSION}&t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${path}`);const j=await r.json();state.cache.set(path,j);return j}
function initMap(){const b=boundsFromBbox(state.manifest.projectBounds);state.map=L.map('map',{minZoom:state.manifest.minZoom||5,zoomSnap:.25,zoomDelta:.5,wheelPxPerZoomLevel:220,scrollWheelZoom:'center',doubleClickZoom:'center',touchZoom:'center',zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false,inertia:false,preferCanvas:false});state.map.createPane('waterPane');state.map.getPane('waterPane').style.zIndex=150;state.map.createPane('riverPane');state.map.getPane('riverPane').style.zIndex=170;state.map.createPane('previousPane');state.map.getPane('previousPane').style.zIndex=360;state.map.createPane('adminPane');state.map.getPane('adminPane').style.zIndex=420;state.map.createPane('hatchPane');state.map.getPane('hatchPane').style.zIndex=430;const c=b.getCenter();state.map.setView(c,state.manifest.minZoom||5,{animate:false});L.control.scale({imperial:false}).addTo(state.map)}
function projectFit(){const b=boundsFromBbox(state.manifest.projectBounds);state.map.setView(b.getCenter(),state.manifest.minZoom||5,{animate:false})}
function applyCategory(){const cat=dom.category.value;state.filtered=state.layers.filter(l=>cat==='all'||l.category===cat);if(!state.filtered.length)state.filtered=[...state.layers];state.filtered.sort((a,b)=>(a.year-b.year)||a.title.localeCompare(b.title,'ru'));if(!state.currentId||!state.filtered.some(l=>l.id===state.currentId)){state.currentId=(state.filtered.find(l=>l.id===state.manifest.defaultLayerId)||state.filtered[state.filtered.length-1])?.id}renderLayerSelect();renderRadios();syncSlider()}
function renderLayerSelect(){dom.layerSelect.innerHTML='';state.filtered.forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=`${m.timeLabel} — ${m.title}`;if(m.id===state.currentId)o.selected=true;dom.layerSelect.appendChild(o)})}
function renderRadios(){dom.radios.innerHTML='';state.filtered.forEach(m=>{const label=document.createElement('label');label.className='radioItem'+(m.id===state.currentId?' active':'');label.innerHTML=`<input type="radio" name="layerRadio" value="${m.id}" ${m.id===state.currentId?'checked':''}><span class="year">${esc(m.timeLabel)}</span><span class="name" title="${esc(m.title)}">${esc(m.title)}</span><span class="count">${fmt.format(m.featureCount)}</span>`;label.querySelector('input').addEventListener('change',()=>selectLayer(m.id));dom.radios.appendChild(label)})}
function syncSlider(){const i=Math.max(0,state.filtered.findIndex(l=>l.id===state.currentId));dom.slider.max=Math.max(0,state.filtered.length-1);dom.slider.value=String(i)}
function idx(){return Math.max(0,state.filtered.findIndex(l=>l.id===state.currentId))}
function geometryType(f){return f?.geometry?.type||''}
function isPointFeature(f){return /Point/.test(geometryType(f))}
function getName(f){const p=f.properties||{};return p._name||p.name||p.Name||p.NAME||p.name_ru||p.name_rus||'объект'}
function getParent(f){const p=f.properties||{};return p._admin_parent||p.admin_parent||p.parent||p.Parent||''}
function getType(f){const p=f.properties||{};return p._unit_type||p.unit_type||p.type||p.Type||p.featurecla||''}
function featureStyle(f,previous=false){if(previous)return{color:'#64748b',weight:1.2,opacity:.78,dashArray:'5 5',fillColor:'#64748b',fillOpacity:.03};const p=f.properties||{};const uncertain=Number(p._uncertain)===1;let fill='#f1c27d';if(dom.mode.value==='parent')fill=colorFor(getParent(f)||'без parent');else if(dom.mode.value==='type')fill=colorFor(getType(f)||'без type');else if(dom.mode.value==='uncertain')fill=uncertain?'#f97316':'#cbd5e1';return{color:uncertain?'#7c2d12':'#243746',weight:uncertain?1.0:1.35,opacity:.98,fillColor:fill,fillOpacity:uncertain?.28:.46}}
function pointStyle(f,previous=false){const p=f.properties||{};const uncertain=Number(p._uncertain)===1;return{radius:previous?4:(uncertain?7:5.5),color:previous?'#64748b':(uncertain?'#7c2d12':'#3a2607'),weight:previous?1:1.4,fillColor:previous?'#94a3b8':(uncertain?'#f97316':'#f6c85f'),fillOpacity:previous?.35:.9,opacity:.98}}
function popup(f){const p=f.properties||{};const keys=['_name','_time_label','_start_year','_end_year','_admin_parent','_unit_type','_population','_source_file','_uncertain_label'].concat(Object.keys(p).filter(k=>!k.startsWith('_')).slice(0,60));const rows=keys.map(k=>`<tr><td>${esc(k)}</td><td>${esc(compact(p[k],240))}</td></tr>`).join('');return `<b>${esc(getName(f))}</b><table class="popupTable">${rows}</table>`}
function onEach(previous=false){return(f,l)=>{l.bindPopup(popup(f),{maxWidth:460});const name=getName(f);if(name){l.bindTooltip(esc(name),{sticky:!dom.showLabels.checked,permanent:dom.showLabels.checked&&!previous,direction:'center',className:'featureLabel'})}if(!previous){l.on('click',()=>selectFeature(f,l));if(l.setStyle){l.on('mouseover',()=>l.setStyle({weight:2.8,fillOpacity:.62}));l.on('mouseout',()=>{if(state.selectedLayer!==l)l.setStyle(featureStyle(f,false))})}}}}
function clearCurrent(){['currentLayer','previousLayer','hatchLayer'].forEach(k=>{if(state[k]){state.map.removeLayer(state[k]);state[k]=null}});state.selectedLayer=null;state.selectedFeature=null}
async function drawPrevious(){if(!dom.showPrevious.checked)return;const i=idx();if(i<=0)return;const meta=state.filtered[i-1];const gj=await loadJson(meta.file);state.previousLayer=L.geoJSON(gj,{pane:'previousPane',style:f=>featureStyle(f,true),pointToLayer:(f,ll)=>L.circleMarker(ll,pointStyle(f,true)),onEachFeature:onEach(true)}).addTo(state.map)}
function ensureHatch(){const svg=document.querySelector('#map .leaflet-overlay-pane svg');if(!svg||svg.querySelector('#simpleHatch'))return;const ns='http://www.w3.org/2000/svg';const defs=document.createElementNS(ns,'defs');const p=document.createElementNS(ns,'pattern');p.setAttribute('id','simpleHatch');p.setAttribute('patternUnits','userSpaceOnUse');p.setAttribute('width','8');p.setAttribute('height','8');p.setAttribute('patternTransform','rotate(45)');const line=document.createElementNS(ns,'line');line.setAttribute('x1','0');line.setAttribute('y1','0');line.setAttribute('x2','0');line.setAttribute('y2','8');line.setAttribute('stroke','#9a3412');line.setAttribute('stroke-width','2');line.setAttribute('opacity','.8');p.appendChild(line);defs.appendChild(p);svg.insertBefore(defs,svg.firstChild)}
async function selectLayer(id){state.currentId=id;state.currentMeta=state.layers.find(l=>l.id===id);if(!state.currentMeta)return;clearCurrent();setStatus(`Загрузка слоя: <b>${esc(state.currentMeta.title)}</b>…`);dom.layerSelect.value=id;renderRadios();syncSlider();await drawPrevious();const gj=await loadJson(state.currentMeta.file);state.currentJson=gj;state.currentLayer=L.geoJSON(gj,{pane:'adminPane',style:f=>featureStyle(f,false),pointToLayer:(f,ll)=>L.circleMarker(ll,pointStyle(f,false)),onEachFeature:onEach(false)}).addTo(state.map);if(dom.showHatch.checked){const hatch={type:'FeatureCollection',features:(gj.features||[]).filter(f=>Number(f.properties?._hatch)===1&&!isPointFeature(f))};if(hatch.features.length){state.hatchLayer=L.geoJSON(hatch,{pane:'hatchPane',interactive:false,style:()=>({color:'transparent',weight:0,opacity:0,fillColor:'url(#simpleHatch)',fillOpacity:.85})}).addTo(state.map);setTimeout(ensureHatch,0)}}renderPanels(gj);fitCurrentLayer(false);setStatus(`Активно: <b>${esc(state.currentMeta.timeLabel)}</b> · ${esc(state.currentMeta.title)} · объектов: ${fmt.format(state.currentMeta.featureCount)} · bbox: ${state.currentMeta.bbox.map(x=>Number(x).toFixed(2)).join(', ')}`)}
function fitCurrentLayer(animated=true){const l=state.currentLayer;if(!l)return;const b=l.getBounds?.();if(b&&b.isValid())state.map.fitBounds(b,{padding:[28,28],maxZoom:7,animate:animated})}
async function drawHydro(){setStatus('Загрузка гидрографии…');const h=state.manifest.hydro;const [water,rivers]=await Promise.all([loadJson(h.water),loadJson(h.rivers)]);state.waterLayer=L.geoJSON(water,{pane:'waterPane',interactive:false,style:{color:'transparent',weight:0,fillColor:'#a9d4e5',fillOpacity:1}});state.riverLayer=L.geoJSON(rivers,{pane:'riverPane',interactive:false,style:f=>{const sw=Number(f.properties?.strokeweig);return{color:'#6aaec7',weight:Number.isFinite(sw)?Math.max(.45,Math.min(1.25,sw*.7)):.65,opacity:.9,lineCap:'round',lineJoin:'round'}}});updateHydro()}
function updateHydro(){if(state.waterLayer){const has=state.map.hasLayer(state.waterLayer);if(dom.showWater.checked&&!has)state.waterLayer.addTo(state.map);if(!dom.showWater.checked&&has)state.map.removeLayer(state.waterLayer)}if(state.riverLayer){const has=state.map.hasLayer(state.riverLayer);if(dom.showRivers.checked&&!has)state.riverLayer.addTo(state.map);if(!dom.showRivers.checked&&has)state.map.removeLayer(state.riverLayer)}}
function selectFeature(f,l){if(state.selectedLayer&&state.selectedLayer.setStyle)state.selectedLayer.setStyle(featureStyle(state.selectedFeature,false));state.selectedLayer=l;state.selectedFeature=f;if(l.setStyle)l.setStyle({color:'#a65b00',weight:3.2,opacity:1,fillOpacity:.68});renderFeature(f)}
function renderFeature(f){const p=f.properties||{};const rows=['_name','_time_label','_start_year','_end_year','_admin_parent','_unit_type','_population','_uncertain_label','_source_file'].map(k=>`<div class="row"><span>${esc(k)}</span><b>${esc(compact(p[k],220))}</b></div>`).join('');const badge=Number(p._uncertain)===1?`<span class="badge warn">спорная/неясная зона</span>`:`<span class="badge">обычный объект</span>`;dom.featureInfo.innerHTML=`${badge}<div class="infoTitle">${esc(getName(f))}</div>${rows}`}
function renderPanels(gj){const feats=gj.features||[];const uncertain=feats.filter(f=>Number(f.properties?._uncertain)===1).length;const bbox=state.currentMeta.bbox||[];dom.layerInfo.innerHTML=`<div class="infoTitle">${esc(state.currentMeta.title)}</div><div class="row"><span>Период</span><b>${esc(state.currentMeta.timeLabel)}</b></div><div class="row"><span>Категория</span><b>${esc(state.currentMeta.category)}</b></div><div class="row"><span>Объектов</span><b>${fmt.format(feats.length)}</b></div><div class="row"><span>Спорных / неясных</span><b>${fmt.format(uncertain)}</b></div><div class="row"><span>Проекция на входе</span><b>${esc(state.currentMeta.projectionMode)}</b></div><div class="row"><span>bbox</span><b>${bbox.map(x=>Number(x).toFixed(3)).join(', ')}</b></div>`;renderSchema(feats);renderTable(feats);dom.featureInfo.innerHTML='Кликни по полигону / объекту.'}
function renderSchema(feats){const stats=new Map();feats.forEach(f=>Object.entries(f.properties||{}).forEach(([k,v])=>{if(!stats.has(k))stats.set(k,{n:0,t:new Set(),s:[]});const st=stats.get(k);if(v!==null&&v!==undefined&&v!==''){st.n++;st.t.add(Array.isArray(v)?'array':typeof v);const sv=String(v);if(st.s.length<2&&!st.s.includes(sv))st.s.push(compact(sv,60))}}));const rows=[...stats.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ru')).map(([k,st])=>`<tr><td>${esc(k)}</td><td>${esc([...st.t].join(', ')||'—')}</td><td>${st.n}/${feats.length}</td><td>${esc(st.s.join(' · ')||'—')}</td></tr>`).join('');dom.schema.innerHTML=`<table class="schemaTable"><thead><tr><th>Поле</th><th>Тип</th><th>Заполнено</th><th>Примеры</th></tr></thead><tbody>${rows}</tbody></table>`}
function renderTable(feats){const q=(dom.search.value||'').toLowerCase();const shown=feats.filter(f=>!q||JSON.stringify(f.properties||{}).toLowerCase().includes(q)).slice(0,250);const rows=shown.map((f,i)=>{const p=f.properties||{};return`<tr data-i="${i}"><td>${i+1}</td><td>${esc(compact(getName(f),70))}</td><td>${esc(compact(getParent(f),70))}</td><td>${esc(compact(getType(f),45))}</td><td>${esc(p._uncertain? p._uncertain_label||'да':'—')}</td></tr>`}).join('');dom.table.innerHTML=`<table class="attrTable"><thead><tr><th>#</th><th>name</th><th>parent</th><th>type</th><th>uncertain</th></tr></thead><tbody>${rows}</tbody></table><div class="muted" style="font-size:11px;margin-top:6px">Показано ${shown.length} из ${feats.length}. Для выбора на карте кликни по объекту.</div>`;dom.table.querySelectorAll('tr[data-i]').forEach(tr=>tr.addEventListener('click',()=>renderFeature(shown[Number(tr.dataset.i)])))}
function bind(){dom.category.addEventListener('change',()=>{applyCategory();selectLayer(state.currentId)});dom.layerSelect.addEventListener('change',e=>selectLayer(e.target.value));dom.mode.addEventListener('change',()=>selectLayer(state.currentId));[dom.showPrevious,dom.showHatch,dom.showLabels].forEach(x=>x.addEventListener('change',()=>selectLayer(state.currentId)));[dom.showWater,dom.showRivers].forEach(x=>x.addEventListener('change',updateHydro));dom.slider.addEventListener('input',e=>{const m=state.filtered[Number(e.target.value)];if(m)selectLayer(m.id)});dom.prev.addEventListener('click',()=>{const i=idx();if(i>0)selectLayer(state.filtered[i-1].id)});dom.next.addEventListener('click',()=>{const i=idx();if(i<state.filtered.length-1)selectLayer(state.filtered[i+1].id)});dom.fitLayer.addEventListener('click',()=>fitCurrentLayer(true));dom.fitProject.addEventListener('click',projectFit);dom.download.addEventListener('click',()=>{if(!state.currentMeta)return;const a=document.createElement('a');a.href=state.currentMeta.file;a.download=state.currentMeta.file.split('/').pop();a.click()});dom.search.addEventListener('input',()=>state.currentJson&&renderTable(state.currentJson.features||[]))}
async function init(){if(!window.L){alert('Leaflet не загрузился. Проверь интернет/CDN или открой проект через GitHub Pages.');return}setStatus('Загрузка manifest…');state.manifest=await loadJson('data/manifest.json');state.layers=[...state.manifest.layers];state.currentId=state.manifest.defaultLayerId;initMap();bind();applyCategory();await selectLayer(state.currentId);drawHydro().catch(err=>setStatus(`Слой открыт, но гидрография не загрузилась: ${esc(err.message)}`))}
init().catch(err=>{console.error(err);setStatus(`<b>Ошибка:</b> ${esc(err.message)}`);alert('Ошибка загрузки: '+err.message)});
