'use strict';
const APP_VERSION='2.0-standardized';
const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat('ru-RU');
const state={manifest:null,layers:[],filtered:[],currentId:null,currentMeta:null,cache:new Map(),currentGeojson:null,map:null,currentLayer:null,hatchLayer:null,previousLayer:null,selected:null,colors:new Map(),lastValues:[]};
const dom={loading:$('loading'),category:$('categoryFilter'),mode:$('modeSelect'),status:$('statusFilter'),showPrevious:$('showPrevious'),showHatch:$('showHatch'),showLabels:$('showLabels'),autoFit:$('autoFit'),timeSlider:$('timeSlider'),radios:$('snapshotRadios'),activeTime:$('activeTimeLabel'),yearBig:$('layerYearBig'),layerInfo:$('layerInfo'),featureInfo:$('featureInfo'),uncertaintyBox:$('uncertaintyBox'),schemaBox:$('schemaBox'),tableBox:$('attributeTableBox'),tableSearch:$('tableSearch'),prevBtn:$('prevBtn'),nextBtn:$('nextBtn'),fitLayerBtn:$('fitLayerBtn'),downloadBtn:$('downloadBtn')};
const palette=['#8dd3c7','#ffffb3','#bebada','#fb8072','#80b1d3','#fdb462','#b3de69','#fccde5','#bc80bd','#ccebc5','#ffed6f','#d9d9d9','#a6cee3','#b2df8a','#fdbf6f'];
const statusColors={normal:'#9ca3af',disputed_affiliation:'#f97316',unclear_affiliation:'#a16207',unstable_control:'#dc2626',disputed_control:'#b45309',unclear_boundary:'#6b7280',transitional_zone:'#7c3aed'};
const categoryLabels={admin:'Административные границы',stats:'Статистика / население',settlements:'Остроги / пункты',points:'Точечные слои',buffer:'Буферы',special:'Спец. ведомства'};
function showLoading(v){dom.loading.classList.toggle('hidden',!v)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function compact(v,n=120){if(v===null||v===undefined||v==='')return '—';const s=String(v);return s.length>n?s.slice(0,n)+'…':s}
function num(v){const n=Number(v);return Number.isFinite(n)?fmt.format(Math.round(n)):'—'}
function pct(v){return v?Math.round(v*1000)/10+'%':'0%'}
function catColor(v){const key=String(v||'—'); if(!state.colors.has(key)) state.colors.set(key,palette[state.colors.size%palette.length]); return state.colors.get(key)}
function bboxToBounds(b){return b?L.latLngBounds([b[1],b[0]],[b[3],b[2]]):null}
function featureId(f){return f?.properties?.feature_id}
function featureLabel(f){const p=f.properties||{};return p.name||p.name_raw||p.admin_parent||'объект'}
function valueColor(v,vals){const n=Number(v); if(!Number.isFinite(n)||!vals.length)return '#cbd5e1'; const min=Math.min(...vals),max=Math.max(...vals); if(max===min)return '#7dd3fc'; const t=(n-min)/(max-min); const ramp=['#f7fbff','#deebf7','#c6dbef','#9ecae1','#6baed6','#3182bd','#08519c']; return ramp[Math.max(0,Math.min(ramp.length-1,Math.floor(t*(ramp.length-1))))]}
async function loadJson(path){if(state.cache.has(path))return state.cache.get(path); showLoading(true); const r=await fetch(`${path}?v=${APP_VERSION}`,{cache:'no-store'}); if(!r.ok)throw new Error(`${r.status} ${path}`); const j=await r.json(); state.cache.set(path,j); showLoading(false); return j}
function initMap(){state.map=L.map('map',{zoomControl:true,preferCanvas:false}); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:12,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map); const b=bboxToBounds(state.manifest.bbox); if(b) state.map.fitBounds(b,{padding:[20,20]}); L.control.scale({imperial:false}).addTo(state.map)}
function ensureHatchPattern(){const svg=document.querySelector('#map .leaflet-overlay-pane svg'); if(!svg||svg.querySelector('#uncertainHatch'))return; const ns='http://www.w3.org/2000/svg'; const defs=document.createElementNS(ns,'defs'); const pat=document.createElementNS(ns,'pattern'); pat.setAttribute('id','uncertainHatch'); pat.setAttribute('patternUnits','userSpaceOnUse'); pat.setAttribute('width','8'); pat.setAttribute('height','8'); pat.setAttribute('patternTransform','rotate(45)'); const line=document.createElementNS(ns,'line'); line.setAttribute('x1','0'); line.setAttribute('y1','0'); line.setAttribute('x2','0'); line.setAttribute('y2','8'); line.setAttribute('stroke','#9a3412'); line.setAttribute('stroke-width','2'); line.setAttribute('opacity','.75'); pat.appendChild(line); defs.appendChild(pat); svg.insertBefore(defs,svg.firstChild)}
function applyFilters(){const cat=dom.category.value; state.filtered=state.layers.filter(l=>cat==='all'||l.category===cat); if(!state.filtered.length) state.filtered=[...state.layers]; state.filtered.sort((a,b)=>(a.sortYear-b.sortYear)||(a.originalOrder-b.originalOrder)); if(!state.currentId||!state.filtered.some(l=>l.id===state.currentId)){const admin=state.filtered.filter(l=>l.category==='admin'); const arr=admin.length?admin:state.filtered; state.currentId=arr[arr.length-1].id} dom.timeSlider.max=Math.max(0,state.filtered.length-1); renderRadios(); syncSlider()}
function renderRadios(){dom.radios.innerHTML=''; state.filtered.forEach((m,i)=>{const el=document.createElement('label'); el.className='snapshot-radio'+(m.id===state.currentId?' active':''); el.innerHTML=`<input type="radio" name="snapshot" value="${m.id}" ${m.id===state.currentId?'checked':''}><span class="time">${esc(m.timeLabel||m.yearLabel||m.sortYear)}</span><span class="name" title="${esc(m.title)}">${esc(m.title)}</span><span class="meta">${fmt.format(m.featureCount)}${m.uncertaintyCount?`<i class="warn-dot" title="${m.uncertaintyCount} спорных"></i>`:''}</span>`; el.querySelector('input').addEventListener('change',()=>selectLayer(m.id)); dom.radios.appendChild(el)})}
function syncSlider(){const idx=Math.max(0,state.filtered.findIndex(l=>l.id===state.currentId)); dom.timeSlider.value=String(idx)}
function currentIndex(){return Math.max(0,state.filtered.findIndex(l=>l.id===state.currentId))}
async function selectLayer(id){state.currentId=id; state.currentMeta=state.layers.find(l=>l.id===id); renderRadios(); syncSlider(); await drawCurrent()}
function filteredFeatures(gj){const v=dom.status.value; if(v==='uncertain')return (gj.features||[]).filter(f=>Number(f.properties?.uncertainty_flag)===1); if(v==='normal')return (gj.features||[]).filter(f=>Number(f.properties?.uncertainty_flag)!==1); return gj.features||[]}
function layerStyle(meta,prev=false){return f=>{const p=f.properties||{}; if(prev)return{color:'#64748b',weight:1.3,opacity:.8,dashArray:'5 5',fillColor:'#94a3b8',fillOpacity:.02}; if(Number(p.render_hatch)===1)return{color:'transparent',weight:0,opacity:0,fillColor:'#fff7ed',fillOpacity:.09}; let fill='#bae6fd'; const mode=dom.mode.value; if(mode==='parent')fill=catColor(p.admin_parent||p.admin_parent_raw||'—'); else if(mode==='unit_type')fill=catColor(p.unit_type||'—'); else if(mode==='status')fill=statusColors[p.uncertainty_code||'normal']||'#9ca3af'; else if(mode==='population')fill=valueColor(p.population,state.lastValues); else if(mode==='confidence')fill=catColor(p.confidence||'—'); return{color:'#31465a',weight:1.35,opacity:.92,fillColor:fill,fillOpacity:.36}}}
function pointLayer(f,latlng,prev=false){const p=f.properties||{}; const uncertain=Number(p.uncertainty_flag)===1; return L.circleMarker(latlng,{radius:prev?4:(uncertain?7:6),color:prev?'#64748b':(uncertain?'transparent':'#3a2607'),weight:prev?1:(uncertain?0:1.4),fillColor:prev?'#94a3b8':(uncertain?'#f97316':'#f6c85f'),fillOpacity:prev?.35:.88,opacity:.95})}
function popupHtml(f){const p=f.properties||{}; const priority=['name','time_label','year','start_year','end_year','admin_parent','unit_type','capital','population','confidence','control_status','uncertainty_source_field','uncertainty_source_text','source_layer']; const rows=priority.concat(Object.keys(p).filter(k=>!priority.includes(k)).slice(0,80)).map(k=>`<tr><td>${esc(k)}</td><td>${esc(compact(p[k],260))}</td></tr>`).join(''); return `<div class="popup-title">${esc(featureLabel(f))}</div><table class="popup-table">${rows}</table>`}
function onEach(meta,prev=false){return(f,l)=>{l.bindPopup(popupHtml(f),{maxWidth:440}); const label=featureLabel(f); if(label){l.bindTooltip(esc(label),{sticky:!dom.showLabels.checked,permanent:dom.showLabels.checked&&!prev,direction:'center',className:'feature-label'})} if(!prev){l.on('click',()=>selectFeature(f,l)); if(l.setStyle){l.on('mouseover',()=>l.setStyle({weight:Number(f.properties?.render_hatch)===1?0:2.8,fillOpacity:.48})); l.on('mouseout',()=>l.setStyle(layerStyle(meta,false)(f)))}}}}
function clearMapLayers(){['currentLayer','hatchLayer','previousLayer'].forEach(k=>{if(state[k]){state.map.removeLayer(state[k]);state[k]=null}})}
async function drawPrevious(){if(!dom.showPrevious.checked)return; const idx=currentIndex(); if(idx<=0)return; const meta=state.filtered[idx-1]; const gj=await loadJson(meta.file); state.previousLayer=L.geoJSON(gj,{style:layerStyle(meta,true),pointToLayer:(f,ll)=>pointLayer(f,ll,true),onEachFeature:onEach(meta,true)}).addTo(state.map)}
async function drawCurrent(){clearMapLayers(); if(!state.currentMeta)return; const meta=state.currentMeta; const gj=await loadJson(meta.file); state.currentGeojson=gj; const feats=filteredFeatures(gj); const display={type:'FeatureCollection',features:feats}; state.lastValues=feats.map(f=>Number(f.properties?.population)).filter(Number.isFinite); await drawPrevious(); state.currentLayer=L.geoJSON(display,{style:layerStyle(meta,false),pointToLayer:(f,ll)=>pointLayer(f,ll,false),onEachFeature:onEach(meta,false)}).addTo(state.map); const hatch={type:'FeatureCollection',features:feats.filter(f=>Number(f.properties?.render_hatch)===1)}; if(dom.showHatch.checked&&hatch.features.length){state.hatchLayer=L.geoJSON(hatch,{interactive:false,style:()=>({color:'transparent',weight:0,opacity:0,fillColor:'url(#uncertainHatch)',fillOpacity:.82})}).addTo(state.map); setTimeout(ensureHatchPattern,0)} if(dom.autoFit.checked){fitCurrentLayer()} updatePanels(display); renderRadios(); dom.activeTime.textContent=meta.timeLabel||meta.yearLabel||meta.sortYear; dom.yearBig.textContent=meta.timeLabel||meta.yearLabel||meta.sortYear; showLoading(false)}
function fitCurrentLayer(){const layer=state.currentLayer||state.previousLayer; if(layer){const b=layer.getBounds?.(); if(b&&b.isValid())state.map.fitBounds(b,{padding:[34,34],maxZoom:7})}}
function selectFeature(f,l){state.selected=f; if(state._selectedLayer&&state._selectedLayer.setStyle)state._selectedLayer.setStyle(layerStyle(state.currentMeta,false)(state._selectedLayer.feature)); state._selectedLayer=l; if(l?.setStyle)l.setStyle({color:'#a65b00',weight:3.2,opacity:1,fillOpacity:.58}); renderFeature(f)}
function renderFeature(f){const p=f.properties||{}; const badge=Number(p.uncertainty_flag)===1?`<span class="badge warn">${esc(p.uncertainty_label)}</span>`:`<span class="badge ok">обычный объект</span>`; const rows=['name','time_label','year','start_year','end_year','admin_parent','unit_type','capital','population','urban_population','rural_population','confidence','source_layer','uncertainty_source_text'].map(k=>`<div class="info-row"><span>${esc(k)}</span><b>${esc(compact(p[k],220))}</b></div>`).join(''); dom.featureInfo.classList.remove('muted'); dom.featureInfo.innerHTML=`${badge}<div class="info-title">${esc(featureLabel(f))}</div>${rows}`}
function renderLayerInfo(gj){const meta=state.currentMeta; const feats=gj.features||[]; const total=feats.length; const uncertain=feats.filter(f=>Number(f.properties?.uncertainty_flag)===1).length; const points=feats.filter(f=>(f.geometry||{}).type==='Point').length; const parents=new Set(feats.map(f=>f.properties?.admin_parent).filter(Boolean)); dom.layerInfo.classList.remove('muted'); dom.layerInfo.innerHTML=`<div class="info-title">${esc(meta.title)}</div><div class="stat-grid"><div class="stat"><div class="k">объектов</div><div class="v">${fmt.format(total)}</div></div><div class="stat"><div class="k">спорных/неясных</div><div class="v">${fmt.format(uncertain)}</div></div><div class="stat"><div class="k">верхний уровень</div><div class="v">${fmt.format(parents.size)}</div></div><div class="stat"><div class="k">точек</div><div class="v">${fmt.format(points)}</div></div></div><div class="info-row"><span>Категория</span><b>${esc(categoryLabels[meta.category]||meta.category)}</b></div><div class="info-row"><span>Период</span><b>${esc(meta.timeLabel||meta.yearLabel)}</b></div><div class="info-row"><span>Файл</span><b>${esc(meta.file)}</b></div>`}
function schemaStats(feats){const stats=new Map(); feats.forEach(f=>Object.entries(f.properties||{}).forEach(([k,v])=>{if(!stats.has(k))stats.set(k,{filled:0,types:new Map(),samples:[]}); const st=stats.get(k); if(v!==null&&v!==undefined&&v!==''){st.filled++; const t=Array.isArray(v)?'array':typeof v; st.types.set(t,(st.types.get(t)||0)+1); const sv=String(v); if(st.samples.length<3&&!st.samples.includes(sv))st.samples.push(compact(sv,80))}})); return [...stats.entries()].map(([name,st])=>({name,filled:st.filled,type:[...st.types.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'null',samples:st.samples}))}
function renderSchema(gj){const feats=gj.features||[]; const rows=schemaStats(feats).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.type)}</td><td>${r.filled}/${feats.length}</td><td>${esc(r.samples.join(' · ')||'—')}</td></tr>`).join(''); dom.schemaBox.classList.remove('muted'); dom.schemaBox.innerHTML=`<table class="schema-table"><thead><tr><th>Поле</th><th>Тип</th><th>Заполнено</th><th>Примеры</th></tr></thead><tbody>${rows}</tbody></table>`}
function renderUncertainty(gj){const list=(gj.features||[]).filter(f=>Number(f.properties?.uncertainty_flag)===1).sort((a,b)=>(a.properties.uncertainty_rank-b.properties.uncertainty_rank)||String(a.properties.name).localeCompare(String(b.properties.name),'ru')); if(!list.length){dom.uncertaintyBox.classList.add('muted');dom.uncertaintyBox.textContent='В текущем срезе не найдено объектов со спорной/неясной/неустойчивой формулировкой.';return} dom.uncertaintyBox.classList.remove('muted'); dom.uncertaintyBox.innerHTML=`<div class="uncertain-list">${list.map(f=>{const p=f.properties;return `<div class="uncertain-item"><b>${esc(p.name)}</b><small>${esc(p.uncertainty_label)} · поле: ${esc(p.uncertainty_source_field||'—')}</small><small>${esc(compact(p.uncertainty_source_text,180))}</small></div>`}).join('')}</div>`}
function renderTable(gj){const feats=gj.features||[]; const q=(dom.tableSearch.value||'').toLowerCase(); const rows=feats.filter(f=>!q||JSON.stringify(f.properties).toLowerCase().includes(q)).map((f,i)=>{const p=f.properties||{};return `<tr data-fid="${esc(featureId(f))}"><td>${i+1}</td><td>${esc(compact(p.name,80))}</td><td>${esc(compact(p.admin_parent,80))}</td><td>${esc(compact(p.unit_type,40))}</td><td>${num(p.population)}</td><td>${esc(p.uncertainty_flag? p.uncertainty_label : '—')}</td></tr>`}).join(''); dom.tableBox.classList.remove('muted'); dom.tableBox.innerHTML=`<table class="attr-table"><thead><tr><th>#</th><th>name</th><th>admin_parent</th><th>unit_type</th><th>population</th><th>uncertainty</th></tr></thead><tbody>${rows}</tbody></table>`; dom.tableBox.querySelectorAll('tr[data-fid]').forEach(tr=>tr.addEventListener('click',()=>{const f=feats.find(x=>featureId(x)===tr.dataset.fid); if(f){renderFeature(f)}}))}
function updatePanels(gj){renderLayerInfo(gj); renderSchema(gj); renderUncertainty(gj); renderTable(gj); if(!state.selected)dom.featureInfo.innerHTML='Кликни по объекту на карте.'}
function downloadCurrent(){if(!state.currentMeta)return; const a=document.createElement('a'); a.href=state.currentMeta.file; a.download=state.currentMeta.file.split('/').pop(); a.click()}
function bindUI(){dom.category.addEventListener('change',()=>{applyFilters();selectLayer(state.currentId)}); [dom.mode,dom.status,dom.showPrevious,dom.showHatch,dom.showLabels].forEach(el=>el.addEventListener('change',drawCurrent)); dom.timeSlider.addEventListener('input',e=>{const m=state.filtered[Number(e.target.value)]; if(m)selectLayer(m.id)}); dom.prevBtn.addEventListener('click',()=>{const i=currentIndex(); if(i>0)selectLayer(state.filtered[i-1].id)}); dom.nextBtn.addEventListener('click',()=>{const i=currentIndex(); if(i<state.filtered.length-1)selectLayer(state.filtered[i+1].id)}); dom.fitLayerBtn.addEventListener('click',fitCurrentLayer); dom.downloadBtn.addEventListener('click',downloadCurrent); dom.tableSearch.addEventListener('input',()=>state.currentGeojson&&renderTable({type:'FeatureCollection',features:filteredFeatures(state.currentGeojson)}))}
async function init(){showLoading(true); state.manifest=await loadJson('data/manifest.json'); state.layers=[...state.manifest.layers].sort((a,b)=>(a.sortYear-b.sortYear)||(a.originalOrder-b.originalOrder)); initMap(); bindUI(); applyFilters(); await selectLayer(state.currentId)}
init().catch(err=>{console.error(err); showLoading(false); alert('Ошибка загрузки: '+err.message)});
